services:

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2025.7.1
    ports: 
      - 8123:8123
    volumes:
      - ${HOMEASSISTANT_VOL_CONFIG}:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: false
    restart: unless-stopped
    depends_on: 
      - mosquitto
      - timescaledb
      - zigbee2mqtt
    networks:
      macvlan1:
        ipv4_address: ${HOMEASSISTANT_IP}

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:2.5.1
    ports: 
      - 8080:8080
    environment:
      - TZ=${TZ}
    volumes:
      - ${ZIGBEE2MQTT_VOL_DATA}:/app/data
    restart: unless-stopped
    depends_on:
      - mosquitto
    networks:
      macvlan1:
        ipv4_address: ${ZIGBEE2MQTT_IP}

  mosquitto:
    image: eclipse-mosquitto:2.0.21-openssl
    ports: 
      - 1883:1883
    volumes:
      - ${MOSQUITTO_VOL_CONFIG}:/mosquitto/config
      - ${MOSQUITTO_VOL_DATA}:/mosquitto/data
      - ${MOSQUITTO_VOL_LOGS}:/mosquitto/logs
    restart: unless-stopped
    networks:
      macvlan1:
        ipv4_address: ${MOSQUITTO_IP}

  timescaledb:
    image: timescale/timescaledb:2.20.3-pg17
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=${TIMESCALEDB_USER}
      - POSTGRES_PASSWORD=${TIMESCALEDB_PASS}
    volumes:
      - ${TIMESCALEDB_VOL_DATA}:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      macvlan1:
        ipv4_address: ${TIMESCALEDB_IP}

  appdaemon:
    image: acockburn/appdaemon:latest
    ports:
      - 5050:5050
    environment:
      - HA_URL=${APPDAEMON_HA_URL}
      - TOKEN=${APPDAEMON_TOKEN}
      - DASH_URL=${APPDAEMON_DASH_URL}
    volumes:
      - ${APPDAEMON_VOL_CONF}:/conf
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      macvlan1:
        ipv4_address: ${APPDAEMON_IP}

  mqttexplorer:
    image: smeagolworms4/mqtt-explorer
    ports: 
      - 4000:4000
    volumes:
      - ${MQTTEXPLORER_VOL_CONFIG}:/mqtt-explorer/config
    restart: unless-stopped
    networks:
      macvlan1:
        ipv4_address: ${MQTTEXPLORER_IP}

  nodered:
    image: nodered/node-red:4.0.9
    ports:
      - 1880:1880
    environment:
      - TZ=${TZ}
    volumes:
      - ${NODERED_VOL_DATA}:/data
    restart: unless-stopped
    depends_on:
      - mosquitto
      - timescaledb
      - homeassistant
    networks:
      macvlan1:
        ipv4_address: ${NODERED_IP}

networks:
  macvlan1:
    driver: macvlan
    driver_opts:
      parent: ${HOST_NET_INTERFACE}
    ipam:
      config:
        - subnet: ${HOST_NET_SUBNET}
          gateway: ${HOST_NET_GATEWAY}
          ip_range: ${HOST_NET_IPRANGE}