services:

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    ports: 
      - 8123:8123
    environment:
      - TZ=${TZ}
    volumes:
      - ${HOMEASSISTANT_VOL_CONFIG}:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: false
    restart: unless-stopped
    depends_on: 
      - mosquitto
      - timescaledb
      - zigbee2mqtt
    deploy:
      resources:
        limits:
          memory: 1g
        reservations: 
          memory: 500m
          
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:2.7.1
    ports: 
      - 8080:8080
    environment:
      - TZ=${TZ}
    volumes:
      - ${ZIGBEE2MQTT_VOL_DATA}:/app/data
    restart: unless-stopped
    depends_on:
      - mosquitto
    deploy:
      resources:
        limits:
          memory: 500m
        reservations: 
          memory: 250m

  mosquitto:
    image: eclipse-mosquitto:2.0.22-openssl
    ports: 
      - 1883:1883
    volumes:
      - ${MOSQUITTO_VOL_CONFIG}:/mosquitto/config
      - ${MOSQUITTO_VOL_DATA}:/mosquitto/data
      - ${MOSQUITTO_VOL_LOGS}:/mosquitto/logs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500m
        reservations: 
          memory: 250m


  mqttexplorer:
    image: smeagolworms4/mqtt-explorer
    ports: 
      - 4000:4000
    volumes:
      - ${MQTTEXPLORER_VOL_CONFIG}:/mqtt-explorer/config
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 250m
        reservations: 
          memory: 125m

#  nodered:
#    image: nodered/node-red:4.0.9
#    ports:
#      - 1880:1880
#    environment:
#      - TZ=${TZ}
#    volumes:
#      - ${NODERED_VOL_DATA}:/data
#    restart: unless-stopped
#    depends_on:
#      - mosquitto
#      - timescaledb
#      - homeassistant
#    networks:
#      macvlan1:
#        ipv4_address: ${NODERED_IP}

#  timescaledb:
#    image: timescale/timescaledb:2.20.3-pg17
#    ports: 
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=${TIMESCALEDB_USER}
#      - POSTGRES_PASSWORD=${TIMESCALEDB_PASS}
#    volumes:
#      - ${TIMESCALEDB_VOL_DATA}:/var/lib/postgresql/data
#    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          memory: 4g
#        reservations: 
#          memory: 2g
